# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "netsensia/ubuntu-trusty64-salt"

    config.vm.network :private_network, ip: "192.168.40.51"

    ["vmware_fusion", "vmware_workstation"].each do |vmware_provider|
      config.vm.provider vmware_provider do |v, override|
        v.vmx["memsize"] = "1024"
        v.vmx["numvcpus"] = "1"
      end
    end

    config.vm.synced_folder "../../../", "/var/www/"
    config.vm.synced_folder "../../../pillar", "/srv/pillar/"
    config.vm.synced_folder "../../salt", "/srv/salt/"

    config.vm.provision "shell", path: "provision.sh"

end
